### ISSUE TITLE
 Uncaught (in promise) TypeError: Class constructor EventEmitter cannot be invoked without 'new'

### ISSUE THREAD

**Issue by morteza-mortezai** [Jenesius/vue-modal#61]
Hi,
I am using Vue 3 Composition api

and , I've done setup as document

But i have this error when I want to open it

![image](https://user-images.githubusercontent.com/75200938/183292817-dda2ebbb-cbff-4a28-9228-ae2114a03da7.png)

`jenesius-vue-modal.cjs.js:495 Uncaught (in promise) TypeError: Class constructor EventEmitter cannot be invoked without 'new'
`

**app.vue**

```
<script setup lang="ts">
import { RouterView } from 'vue-router'
import {container} from "jenesius-vue-modal";
</script>

<template>
 <container  />
  <RouterView />
</template>
```

**homeComponent.vue**

```
import { openModal } from "jenesius-vue-modal";
import MyCom from '@/components/Common/MyCom.vue'

function open() {
  openModal(MyCom, { message: "Welcome" })
}
```

MyCom.vue
```
<script setup lang="ts">
</script>
<template>
  <div class="header1">
    Hello
  </div>
</template>
```

How can I fix this ?

**Comment by Barakuda91** [comment]
I have this problem too.
What do you advise ?

**Comment by Jenesius** [comment]
Thank you for opening the issue, I really appreciate it!
The problem was using the ES6 standard in the EventEmitter class.
I resolve this problem with **1.7.0** version:
`npm i jenesius-vue-modal@1.7.0` for check solution.
- removing EventEmitter (override modal.on method)
- add test for checking unsubscribe function

@Barakuda91 , @morteza-mortezai I test the last version of library - its working. If someone can update and test it - i will be happy.

**Comment by Barakuda91** [comment]
Ща тестану
Пока что временно откатился на более стабильную 1.5.0

**Comment by Barakuda91** [comment]
Works great! Thank!
